# *************
# *** Rules ***
# *************

all: $(OBJECT_FILE_START_ASM) $(OBJECT_FILE_START_CPP) $(NEBULA_BIN) $(NEBULA_IMG)

run: $(NEBULA_IMG)
	$(QEMU) $(QEMUFLAGS) ./$<

clean:
	$(RM) $(OBJECT_FILE_START_ASM) $(OBJECT_FILE_START_CPP) $(NEBULA_BIN) $(NEBULA_IMG)
	$(RM) $(FIND_OBJECT_FILES_SC_C) $(FIND_OBJECT_FILES_MMU_C) $(FIND_OBJECT_FILES_IPC_C) $(FIND_OBJECT_FILES_ISR_C) $(FIND_OBJECT_FILES_TMM_C)
	$(RM) $(FIND_OBJECT_FILES_SC_ASM) $(FIND_OBJECT_FILES_MMU_ASM) $(FIND_OBJECT_FILES_IPC_ASM) $(FIND_OBJECT_FILES_ISR_ASM) $(FIND_OBJECT_FILES_TMM_ASM)
	$(RM) $(FIND_OBJECT_FILES_SC_CPP) $(FIND_OBJECT_FILES_MMU_CPP) $(FIND_OBJECT_FILES_IPC_CPP) $(FIND_OBJECT_FILES_ISR_CPP) $(FIND_OBJECT_FILES_TMM_CPP)

distclean:
	rm -rf build